---
title: "Assignment-06"
author: "Ke'Shondra Reed"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)

options(width = 683)

library(dplyr)
library(ggplot2)
library(tidyverse)
library(HelpersMG)
library(scales)
library(ggpmisc)
```

```{r download}
if(!file.exists("./raw_data/owid-covid-data.csv")) {
  wget(url = "https://covid.ourworldindata.org/data/owid-covid-data.csv", destfile = "./raw_data/owid-covid-data.csv")
}
```
```{r tidyCountry}

read_csv("./raw_data/owid-covid-data.csv") %>%
  filter(date == "2020-06-30") %>%
  select(Country = location, Diabetes_Prevalence = diabetes_prevalence, Over_70 = aged_70_older, Total_Deaths = total_deaths, Per_Million_Total_Deaths = total_deaths_per_million) %>%
  filter(Country != "World") %>%
  write.table(file = "./output/june_deaths_by_country.csv", row.names = FALSE, sep = ",")

```


```{r Continent}
read_csv("./raw_data/owid-covid-data.csv") %>%
  filter(continent == "Europe") %>%
  select(Country = location, Date = date, Total_Deaths = total_deaths, Per_Million_Total_Deaths = total_deaths_per_million) %>%
  write.table(file = "./output/european_deaths_by_date.csv", row.names = FALSE, sep = ",")

```

```{r diabetes, fig.cap = "**Figure 1:** COVID Deaths by Diabetes Prevalence", fig.align = "left"}
ggplot(data = read_csv("./output/june_deaths_by_country.csv"), aes(x = Diabetes_Prevalence, y = Total_Deaths)) + geom_point() + labs(x = "Diabetes Prevalence (%)", y = "Total Deaths") + theme_linedraw() + scale_y_continuous(labels = scales::comma) + xlim(0,25) + ylim(0,150000)
```
In Figure 1 the relationship between the presence of diabetesand the total deaths are not the strong.
 
<br/>
<br/>

```{r deaths_over_70, fig.cap = "**Figure 2:** COVID-19 Deaths of People Over 70", fig.align = "left"}

ggplot(data = read_csv("./output/june_deaths_by_country.csv"), aes(x = Over_70, y = Total_Deaths)) + geom_point() + labs(x = "% Population over 70", y = "Total Deaths") + theme_linedraw() + scale_y_continuous(labels = scales::comma) + xlim(0,20) + ylim(0,150000)


```
In Figure 2 the relationship between an older population of people over 70 and the total numbers of deaths are much clearer. 

<br/>

```{r european_Deathdate, fig.cap = "**Figure 3:** COVID-19 Deaths by Date in European Countries"}

ggplot(data = read_csv("./output/european_deaths_by_date.csv"), aes(x = Date, y = Total_Deaths, color = Country)) + geom_line() + labs(x = "Date", y = "Total Deaths") + theme_linedraw() + scale_y_continuous(labels = scales::comma) + ylim(0,50000)



```
In Figure 3 on March, 13,2020, Italy was the first to have over 1,000 deaths from COVID-19.
<br/>
<br/>
<br/>


